[project]
name = "ml-note"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "instar94", email = "stright94@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.136.1",
]

[project.scripts]
ml-note = "ml_note:main"

[build-system]
requires = ["uv_build>=0.11.14,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "pytest>=9.0.3",
    "ruff>=0.15.13",
]
